### ISSUE TITLE
Change default values to have unlimited retries

### ISSUE THREAD

**Issue by kevindong** [lestrrat-go/backoff#12]
By default, this library will quit attempting to retry after 10 attempts. A more sane default would be an unlimited number of retries unless the `WithMaxRetries` option is invoked. 

If not, you should at least explicitly mention in the README that the default value is 10. I recognize that you do document the default value in the Godocs, but realistically most people are just going to copy paste the example you have in the README.

**Comment by lestrrat** [comment]
Let me first take the low hanging fruit, which is the README. working on it...

**Comment by lestrrat** [comment]
Let me ponder on the default value. At this point, I think "retry forever" should be explicit.

**Comment by lestrrat** [comment]
I think I will punt changing the default value. My next best fallback would be to provide a `backoff.SetDefaultMaxRetries(n)` function so that users can change the default behavior. But I don't know if this is what you need/want...

anyway, the README has been slightly tweaked, so closing this issue for now.
